/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author others
 */
public class Admin extends javax.swing.JFrame {
String depatment ="";
    /**
     * Creates new form Admin
     */
    DatabaseConnection databaseConnection = new DatabaseConnection();
    Connection con = databaseConnection.myConnection();
    private String use;
    public Admin() {
        initComponents();
        setLocationRelativeTo(null);
   
    }
   
            
          
            // TODO add your handling code here:
            
                    
            
            
            
            
       
            
            
            
        
                  
    public void admin_id(String use){
        String a = use;
        jLabel39_id.setText(a);
        try {
            
            String sql ="select * from admin where ad_id= ?";
            PreparedStatement  pstmt = con.prepareStatement(sql);
            pstmt.setString(1,jLabel39_id.getText());
            
           ResultSet rs = pstmt.executeQuery();
           if(rs.next()){
           jLabel39_id.setText(a);
            jLabel40.setText(rs.getString("f_name"));
            jLabel42.setText(rs.getString("l_name"));
            jTextField13.setText(rs.getString("email"));
            jLabel43.setText(rs.getString("deparment"));
            jTextField3.setText(rs.getString("password"));
                String depatment = rs.getString("deparment");
           }
            
            
            //String sql = "select * from subject where sub_id=?";            
            //PreparedStatement pstmt = con.prepareStatement(sql);
            //pstmt.setString(1,jTextField26.getText());
            //ResultSet rs = pstmt.executeQuery();
            //JOptionPane.showMessageDialog(this,"user details updated");
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel56 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39_id = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel58 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jLabel61 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton8 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel57 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jTextField26 = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton17 = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/ruhuna.jpg"))); // NOI18N
        jLabel56.setText("jLabel56");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255), 3));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMIN PAGE");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Add User");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Add Course");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Timetable");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("New Notices");

        jButton1.setText("Create New  User");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("View / Delete / Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Create New Course");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Create Time Table");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("create  New notice or delete notice");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton4.setText("View / Delete / Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton21.setText("logout");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setText("profile");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton21)
                    .addComponent(jButton22))
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 290, 520));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("User ID");
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 90, 20));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Last Name");
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 90, 20));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("First Name");
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 90, 20));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Email");
        jPanel8.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 80, 20));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Deparment");
        jPanel8.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 110, 20));

        jLabel39_id.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39_id.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39_id.setText("jLabel39");
        jPanel8.add(jLabel39_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 210, 30));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("jLabel40");
        jPanel8.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 180, 20));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("jLabel42");
        jPanel8.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 170, 30));

        jTextField13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel8.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 190, 30));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("jLabel43");
        jPanel8.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 190, 20));

        jButton15.setText("Update Profile");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 110, 30));

        jDesktopPane2.setLayer(jLabel58, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel58, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel58, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 160, 130));

        jButton20.setText("choose the image");
        jPanel8.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 140, -1));

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("password");
        jPanel8.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 100, 30));
        jPanel8.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 190, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/Capture.JPG"))); // NOI18N
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("jLabel41");
        jPanel8.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 120, 20));

        jTabbedPane2.addTab("tab1", jPanel8);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Post");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STUDENT", "LECTURER", "TECHNICAL", "ADMIN" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel9.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 280, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("User Id");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        jPanel9.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 280, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("First name");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 70, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Last Name");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 70, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Email");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 60, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Deparment");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Password");
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BST", "ICT", "ET" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel9.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 330, 30));
        jPanel9.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 280, 30));
        jPanel9.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 280, 30));
        jPanel9.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 330, 30));

        jButton8.setText("Create");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 150, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Createing Users");
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 450, 30));
        jPanel9.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 330, 30));

        jDesktopPane1.setLayer(jLabel57, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 150, 110));

        jButton19.setText("choose the image");
        jPanel9.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 130, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/Capture.JPG"))); // NOI18N
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        jTextField6.setText("jTextField6");
        jPanel9.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 160, 20));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("User Id");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jTextField4.setText("jTextField4");
        jPanel9.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 160, 30));

        jTabbedPane2.addTab("tab2", jPanel9);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("View / Delete / Update User");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 290, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("First name");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 140, 20));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("ID");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, 20));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, 30));

        jButton9.setText("search");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 70, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("last name");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 90, -1));

        jButton10.setText("Update");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 70, -1));

        jButton11.setText("Delete");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 70, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "post", "user id", "first name", "last name", "Email", "deparment", "Password"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 550, 80));
        jPanel2.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 180, 30));

        jTextField22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 180, 30));

        jTextField23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 180, 30));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Email");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 80, 20));

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Departtment");
        jPanel2.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 90, 20));

        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 180, 30));

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("password");
        jPanel2.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 90, 30));
        jPanel2.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 180, 30));

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("post");
        jPanel2.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 70, 20));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STUDENT", "TECHNICAL", "LECTURER" }));
        jPanel2.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 180, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/Capture.JPG"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane2.addTab("tab3", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Creating  Subject");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 200, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Subject Code");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Subject name");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 130, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Subject credit");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Department");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 80, 20));
        jPanel3.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 270, 30));
        jPanel3.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 270, 30));
        jPanel3.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 270, 30));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BST", "ICT", "ET" }));
        jPanel3.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 270, 30));

        jButton3.setText("Create");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 120, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/Capture.JPG"))); // NOI18N
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTextField9.setText("jTextField8");
        jPanel3.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 240, 30));

        jTabbedPane2.addTab("tab4", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("View / Update  /  Delete  subject");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 400, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "subject code", "subject cource", "credit", "department id"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 460, 80));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Search By ID");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, -1));

        jButton12.setText("Search");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 100, -1));

        jButton13.setText("Delete");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 100, -1));

        jButton14.setText("Update");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 100, -1));
        jPanel4.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 180, 30));

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("subject name");
        jPanel4.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, 20));
        jPanel4.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 180, 30));

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("credit");
        jPanel4.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 110, 30));
        jPanel4.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 180, 30));

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("depatment id");
        jPanel4.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 100, 30));
        jPanel4.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 180, 30));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/Capture.JPG"))); // NOI18N
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 575, 482));

        jTabbedPane2.addTab("tab5", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ICT", "BST", "ET" }));
        jPanel5.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 240, 30));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Create Or Update Table");
        jPanel5.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 260, 40));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Time");
        jPanel5.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 150, 20));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Day");
        jPanel5.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 120, 30));

        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("plz Enter first 3 digit in simple letter");
        jPanel5.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 230, 20));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Subject");
        jPanel5.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));
        jPanel5.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 240, 30));

        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Like 8.00 - 9.00 ");
        jPanel5.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 300, -1));

        jButton16.setText("Add Time table");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mon", "tue", "wed", "thu", "fri" }));
        jPanel5.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 230, 30));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8.00-9.00", "9.00-10.00", "10.00-11.00", "11.00-12.00", "12.00-13.00", "14.00-15.00", "15.00-16.00" }));
        jPanel5.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 230, 30));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/Capture.JPG"))); // NOI18N
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane2.addTab("tab6", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Create notices or Delete Notices");
        jPanel6.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 340, 40));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Topic");
        jPanel6.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 70, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Notice no");
        jPanel6.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 90, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Date");
        jPanel6.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 70, 30));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Details");
        jPanel6.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        jPanel6.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 230, 30));
        jPanel6.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 230, 30));
        jPanel6.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 230, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 230, 100));

        jButton17.setText("Add notice");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 90, -1));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Search Notice No ");
        jPanel6.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 130, 20));
        jPanel6.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 230, 30));

        jButton18.setText("Delete notice");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/Capture.JPG"))); // NOI18N
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/ruhuna.jpg"))); // NOI18N
        jPanel6.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 40));

        jTabbedPane2.addTab("tab7", jPanel6);

        jPanel1.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 580, 490));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/login page2.jpg"))); // NOI18N
        jLabel1.setText("Time Table");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            // TODO add your handling code here:
           jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(3);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(4);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(5);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(6);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       
        try {
            
            String post = jComboBox1.getSelectedItem().toString();
            if("STUDENT".equals(post)){
                    String sql1 = "insert into student values(?,?,?,?,?,?)";
                    PreparedStatement  pstmt1 = con.prepareStatement(sql1);
                    pstmt1.setString(1,jTextField1.getText());
                    pstmt1.setString(2,jTextField2.getText());
                    pstmt1.setString(3,jTextField5.getText());
                    pstmt1.setString(4,jTextField12.getText());

                    String dep=jComboBox2.getSelectedItem().toString();
                    String depatment="";
                    if("BST".equals(dep)){
                        depatment = "d03";
                    }
                    if("ICT".equals(dep)){
                        depatment = "d01";
                    }
                    if("ET".equals(dep)){
                        depatment = "d02";
                    }


                    pstmt1.setString(5,depatment);
                    pstmt1.setString(6,jPasswordField1.getText());

                    pstmt1.execute();
            
            }
            
            
            
            if(post == "LECTURER"){
                    String sql1 = "insert into lecturer values(?,?,?,?,?,?)";
                    PreparedStatement  pstmt1 = con.prepareStatement(sql1);
                    pstmt1.setString(1,jTextField1.getText());
                    pstmt1.setString(2,jTextField2.getText());
                    pstmt1.setString(3,jTextField5.getText());
                    pstmt1.setString(4,jTextField12.getText());

                    String dep=jComboBox2.getSelectedItem().toString();
                    String depatment="";
                    if("BST".equals(dep)){
                        depatment = "d03";
                    }
                    if("ICT".equals(dep)){
                        depatment = "d01";
                    }
                    if("ET".equals(dep)){
                        depatment = "d02";
                    }


                    pstmt1.setString(5,depatment);
                    pstmt1.setString(6,jPasswordField1.getText());

                    pstmt1.execute();
            
            }
            
            if(post == "TECHNICAL"){
                    String sql1 = "insert into technical_officer values(?,?,?,?,?,?)";
                    PreparedStatement  pstmt1 = con.prepareStatement(sql1);
                    pstmt1.setString(1,jTextField1.getText());
                    pstmt1.setString(2,jTextField2.getText());
                    pstmt1.setString(3,jTextField5.getText());
                    pstmt1.setString(4,jTextField12.getText());

                    String dep=jComboBox2.getSelectedItem().toString();
                    String depatment="";
                    if("BST".equals(dep)){
                        depatment = "d03";
                    }
                    if("ICT".equals(dep)){
                        depatment = "d01";
                    }
                    if("ET".equals(dep)){
                        depatment = "d02";
                    }


                    pstmt1.setString(5,depatment);
                    pstmt1.setString(6,jPasswordField1.getText());

                    pstmt1.execute();
            
            }
            if(post == "ADMIN"){
                    String sql1 = "insert into admin values(?,?,?,?,?,?)";
                    PreparedStatement  pstmt1 = con.prepareStatement(sql1);
                    pstmt1.setString(1,jTextField1.getText());
                    pstmt1.setString(2,jTextField2.getText());
                    pstmt1.setString(3,jTextField5.getText());
                    pstmt1.setString(4,jTextField12.getText());

                    String dep=jComboBox2.getSelectedItem().toString();
                    String depatment="";
                    if("BST".equals(dep)){
                        depatment = "d03";
                    }
                    if("ICT".equals(dep)){
                        depatment = "d01";
                    }
                    if("ET".equals(dep)){
                        depatment = "d02";
                    }


                    pstmt1.setString(5,depatment);
                    pstmt1.setString(6,jPasswordField1.getText());

                    pstmt1.execute();
            
            }
            
            
            
            
            
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
    
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
          
       String post1 =  jComboBox7.getSelectedItem().toString();
          try {  
            
            if("STUDENT".equals(post1)){
                
                    String sql = "select * from student where st_id=?";            
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,jTextField7.getText());
                    ResultSet rs = pstmt.executeQuery();
                    jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                    ResultSet rp = pstmt.executeQuery();
                    if(rp.next()){
                    
                    jTextField21.setText(rp.getString("f_name"));
                    jTextField22.setText(rp.getString("l_name"));
                    jTextField23.setText(rp.getString("email"));
                    jTextField24.setText(rp.getString("deparment"));
                    jTextField25.setText(rp.getString("password"));
                 }
            }
            
            if("LECTURER".equals(post1)){
                String sql = "select * from lecturer where lec_id=?";            
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,jTextField7.getText());
                    ResultSet rs = pstmt.executeQuery();
                    jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                    ResultSet rp = pstmt.executeQuery();
                    if(rp.next()){
                    
                    jTextField21.setText(rp.getString("f_name"));
                    jTextField22.setText(rp.getString("l_name"));
                    jTextField23.setText(rp.getString("email"));
                    jTextField24.setText(rp.getString("deparment"));
                    jTextField25.setText(rp.getString("password"));
                 }
            
            }
            
            if("TECHNICAL".equals(post1)){
                String sql = "select * from technical_officer where tec_id=?";            
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,jTextField7.getText());
                    ResultSet rs = pstmt.executeQuery();
                    jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                    ResultSet rp = pstmt.executeQuery();
                    if(rp.next()){
                    
                    jTextField21.setText(rp.getString("f_name"));
                    jTextField22.setText(rp.getString("l_name"));
                    jTextField23.setText(rp.getString("email"));
                    jTextField24.setText(rp.getString("deparment"));
                    jTextField25.setText(rp.getString("password"));
                 }
            }
            
             } catch (SQLException ex) {
                    Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);          
             }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        
        
        //DefaultTableModel mi = (DefaultTableModel)jTable2.getModel();
        
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            String post1 =  jComboBox7.getSelectedItem().toString();
            if("STUDENT".equals(post1)){
                String sql ="update student set f_name = ?,l_name =?,email=?, deparment=?, password=? where st_id= ?";
                PreparedStatement  pstmt = con.prepareStatement(sql);
                pstmt.setString(1,jTextField21.getText());
                pstmt.setString(2,jTextField22.getText());
                pstmt.setString(3,jTextField23.getText());
                pstmt.setString(4,jTextField24.getText());
                pstmt.setString(5,jTextField25.getText());
                pstmt.setString(6,jTextField7.getText());
                pstmt.execute();
                JOptionPane.showMessageDialog(this,"user details updated");
            
            }
            if("LECTURER".equals(post1)){
                String sql ="update lecturer set f_name = ?,l_name =?,email=?, deparment=?, password=? where lec_id= ?";
                PreparedStatement  pstmt = con.prepareStatement(sql);
                pstmt.setString(1,jTextField21.getText());
                pstmt.setString(2,jTextField22.getText());
                pstmt.setString(3,jTextField23.getText());
                pstmt.setString(4,jTextField24.getText());
                pstmt.setString(5,jTextField25.getText());
                pstmt.setString(6,jTextField7.getText());
                pstmt.execute();
                JOptionPane.showMessageDialog(this,"user details updated");
            
            }
            if("ADMIN".equals(post1)){
                String sql ="update admin set f_name = ?,l_name =?,email=?, deparment=?, password=? where ad_id= ?";
                PreparedStatement  pstmt = con.prepareStatement(sql);
                pstmt.setString(1,jTextField21.getText());
                pstmt.setString(2,jTextField22.getText());
                pstmt.setString(3,jTextField23.getText());
                pstmt.setString(4,jTextField24.getText());
                pstmt.setString(5,jTextField25.getText());
                pstmt.setString(6,jTextField7.getText());
                pstmt.execute();
                JOptionPane.showMessageDialog(this,"user details updated");
            
            }
            if("TECHNICAL".equals(post1)){
                String sql ="update technical_officer set f_name = ?,l_name =?,email=?, deparment=?, password=? where tec_id= ?";
                PreparedStatement  pstmt = con.prepareStatement(sql);
                pstmt.setString(1,jTextField21.getText());
                pstmt.setString(2,jTextField22.getText());
                pstmt.setString(3,jTextField23.getText());
                pstmt.setString(4,jTextField24.getText());
                pstmt.setString(5,jTextField25.getText());
                pstmt.setString(6,jTextField7.getText());
                pstmt.execute();
                JOptionPane.showMessageDialog(this,"user details updated");
            }
            
            
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "insert into subject values(?,?,?,?)";
            PreparedStatement  pstmt = con.prepareStatement(sql);
            pstmt.setString(1,jTextField8.getText());
            pstmt.setString(2,jTextField10.getText());
            pstmt.setString(3,jTextField11.getText());
           
            
            String dep=jComboBox2.getSelectedItem().toString();
            String depatment="";
            if("BST".equals(dep)){
                depatment = "d03";
            }
            if("ICT".equals(dep)){
                depatment = "d01";
            }
            if("ET".equals(dep)){
                depatment = "d02";
            }
            
            
            pstmt.setString(4,depatment);
           
            
            pstmt.execute();
            
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
    
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try {
            // TODO add your handling code here:
            String sql = "DELETE FROM subject WHERE sub_id=?";
            PreparedStatement  pstmt = con.prepareStatement(sql);
            pstmt.setString(1,jTextField26.getText());
            pstmt.execute();
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
            // TODO add your handling code here:
            String sql = "select * from subject where sub_id=?";            
            PreparedStatement pstmt = con.prepareStatement(sql);
            pstmt.setString(1,jTextField26.getText());
            ResultSet rs = pstmt.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            ResultSet rp = pstmt.executeQuery();
            if(rp.next()){
                   
                    jTextField14.setText(rp.getString("sub_name"));
                    jTextField15.setText(rp.getString("credit"));
                    jTextField27.setText(rp.getString("dept_id"));
                   
                    
            }
            
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
                  
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        try {
                
           
            
            String dep=jComboBox6.getSelectedItem().toString();
            String day=jComboBox3.getSelectedItem().toString();
            String depatment="";
            if("BST".equals(dep)){
                depatment = "d03";
            
              if("mon".equals(day)){
                   
                    String time = jComboBox4.getSelectedItem().toString();
                    String sql ="update bst_time_table set mon = ? where time= ?";
                    PreparedStatement  pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,jTextField16.getText());
                    pstmt.setString(2,jComboBox4.getSelectedItem().toString());
                    pstmt.execute();
                    JOptionPane.showMessageDialog(this,"BST time table updated");

            
               }
               if("tue".equals(day)){
                   String sql ="update bst_time_table set tue = ? where time= ?";
                    PreparedStatement  pstmt = con.prepareStatement(sql);
                   
                    pstmt.setString(1,jTextField16.getText());
                    pstmt.setString(2,jComboBox4.getSelectedItem().toString());
                    pstmt.execute();
                    JOptionPane.showMessageDialog(this,"BST time table updated");
               } 
               if("wed".equals(day)){
                   String sql ="update bst_time_table set wed = ? where time= ?";
                    PreparedStatement  pstmt = con.prepareStatement(sql);
                   
                    pstmt.setString(1,jTextField16.getText());
                    pstmt.setString(2,jComboBox4.getSelectedItem().toString());
                    pstmt.execute();
                    JOptionPane.showMessageDialog(this,"BST time table updated");
               } 
               if("thu".equals(day)){
                   String sql ="update bst_time_table set thu = ? where time= ?";
                    PreparedStatement  pstmt = con.prepareStatement(sql);
                   
                    pstmt.setString(1,jTextField16.getText());
                    pstmt.setString(2,jComboBox4.getSelectedItem().toString());
                    pstmt.execute();
                    JOptionPane.showMessageDialog(this,"BST time table updated");
               } 
               if("fri".equals(day)){
                   String sql ="update bst_time_table set fri = ? where time= ?";
                    PreparedStatement  pstmt = con.prepareStatement(sql);
                   
                    pstmt.setString(1,jTextField16.getText());
                    pstmt.setString(2,jComboBox4.getSelectedItem().toString());
                    pstmt.execute();
                    JOptionPane.showMessageDialog(this,"BST time table updated");
               } 
               
                
            }
            if("ICT".equals(dep)){
                depatment = "d01";
               if("mon".equals(day)){
                   
                    String time = jComboBox4.getSelectedItem().toString();
                    
                    String sql ="update ict_time_table set mon = ? where time= ?";
                    PreparedStatement  pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,jTextField16.getText());
                    pstmt.setString(2,jComboBox4.getSelectedItem().toString());
                    
                    pstmt.execute();
                    JOptionPane.showMessageDialog(this,"ict time table updated");
            
               }
               if("tue".equals(day)){
                   String sql ="update ict_time_table set tue = ? where time= ?";
                    PreparedStatement  pstmt = con.prepareStatement(sql);
                   
                    pstmt.setString(1,jTextField16.getText());
                    pstmt.setString(2,jComboBox4.getSelectedItem().toString());
                    pstmt.execute();
                    JOptionPane.showMessageDialog(this,"ict time table updated");
               } 
               if("wed".equals(day)){
                   String sql ="update ict_time_table set wed = ? where time= ?";
                    PreparedStatement  pstmt = con.prepareStatement(sql);
                   
                    pstmt.setString(1,jTextField16.getText());
                    pstmt.setString(2,jComboBox4.getSelectedItem().toString());
                    pstmt.execute();
                    JOptionPane.showMessageDialog(this,"ict time table updated");
               } 
               if("thu".equals(day)){
                   String sql ="update ict_time_table set thu = ? where time= ?";
                    PreparedStatement  pstmt = con.prepareStatement(sql);
                   
                    pstmt.setString(1,jTextField16.getText());
                    pstmt.setString(2,jComboBox4.getSelectedItem().toString());
                    pstmt.execute();
                    JOptionPane.showMessageDialog(this,"ict time table updated");
               } 
               if("fri".equals(day)){
                   String sql ="update ict_time_table set fri = ? where time= ?";
                    PreparedStatement  pstmt = con.prepareStatement(sql);
                   
                    pstmt.setString(1,jTextField16.getText());
                    pstmt.setString(2,jComboBox4.getSelectedItem().toString());
                    pstmt.execute();
                    JOptionPane.showMessageDialog(this,"ict time table updated");
               } 
                
            }
            if("ET".equals(dep)){
                depatment = "d02";
                if("mon".equals(day)){
                   
                    String time = jComboBox4.getSelectedItem().toString();
                    
                    String sql ="update ent_time_table set mon = ? where time= ?";
                    PreparedStatement  pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,jTextField16.getText());
                    pstmt.setString(2,jComboBox4.getSelectedItem().toString());
                    
                    pstmt.execute();
                    JOptionPane.showMessageDialog(this,"ent time table updated");

            
               }
               if("tue".equals(day)){
                   String sql ="update ent_time_table set tue = ? where time= ?";
                    PreparedStatement  pstmt = con.prepareStatement(sql);
                   
                    pstmt.setString(1,jTextField16.getText());
                    pstmt.setString(2,jComboBox4.getSelectedItem().toString());
                    pstmt.execute();
                    JOptionPane.showMessageDialog(this,"ent time table updated");
               } 
               if("wed".equals(day)){
                   String sql ="update ent_time_table set wed = ? where time= ?";
                    PreparedStatement  pstmt = con.prepareStatement(sql);
                   
                    pstmt.setString(1,jTextField16.getText());
                    pstmt.setString(2,jComboBox4.getSelectedItem().toString());
                    pstmt.execute();
                    JOptionPane.showMessageDialog(this,"ent time table updated");
               } 
               if("thu".equals(day)){
                   String sql ="update ent_time_table set thu = ? where time= ?";
                    PreparedStatement  pstmt = con.prepareStatement(sql);
                   
                    pstmt.setString(1,jTextField16.getText());
                    pstmt.setString(2,jComboBox4.getSelectedItem().toString());
                    pstmt.execute();
                    JOptionPane.showMessageDialog(this,"ent time table updated");
               } 
               if("fri".equals(day)){
                   String sql ="update ent_time_table set fri = ? where time= ?";
                    PreparedStatement  pstmt = con.prepareStatement(sql);
                   
                    pstmt.setString(1,jTextField16.getText());
                    pstmt.setString(2,jComboBox4.getSelectedItem().toString());
                    pstmt.execute();
                    JOptionPane.showMessageDialog(this,"ent time table updated");
               } 
            }
            
               
           
            
           
            
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
    
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
            try {
            String sql = "insert into notice values(?,?,?,?)";
            PreparedStatement  pstmt = con.prepareStatement(sql);
            pstmt.setString(1,jTextField17.getText());
            pstmt.setString(2,jTextField18.getText());
            pstmt.setString(3,jTextField19.getText());
            pstmt.setString(4,jTextArea1.getText());
            pstmt.execute();
            JOptionPane.showMessageDialog(this,"new notice added");
            
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
    
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        try {
            // TODO add your handling code here:
            String sql = "DELETE FROM notice WHERE no_id=?";
            PreparedStatement  pstmt = con.prepareStatement(sql);
            pstmt.setString(1,jTextField20.getText());
            pstmt.execute();
            JOptionPane.showMessageDialog(this,"notice deleted");
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
            
        try {
            String sql ="update admin set password = ? , email = ? where ad_id = ?";
            PreparedStatement  pstmt = con.prepareStatement(sql);
            
            //pstmt.setString(1,jTextField13.getText());
            pstmt.setString(1,jTextField3.getText());
            pstmt.setString(2,jTextField13.getText());
            pstmt.setString(3,jLabel39_id.getText());
            
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this,"users details updated");
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
            String post1 = jComboBox7.getSelectedItem().toString();     
        try {
            if("STUDENT".equals(post1)){
                String sql ="DELETE FROM student WHERE st_id=?";
                PreparedStatement  pstmt = con.prepareStatement(sql);
                pstmt.setString(1,jTextField7.getText());
                pstmt.execute();
                JOptionPane.showMessageDialog(this,"users deleted");
                
              
            
            }
            if("LECTURER".equals(post1)){
                String sql ="DELETE FROM lecturer WHERE lec_id=?";
                PreparedStatement  pstmt = con.prepareStatement(sql);
                pstmt.setString(1,jTextField7.getText());
                pstmt.execute();
                JOptionPane.showMessageDialog(this,"users deleted");
            
            }
            if("ADMIN".equals(post1)){
                String sql ="DELETE FROM admin WHERE ad_id=?";
                PreparedStatement  pstmt = con.prepareStatement(sql);
                pstmt.setString(1,jTextField7.getText());
                pstmt.execute();
                JOptionPane.showMessageDialog(this,"users deleted");
            
            }
            if("TECHNICAL".equals(post1)){
                String sql ="DELETE FROM technical_officer WHERE tec_id=?";
                PreparedStatement  pstmt = con.prepareStatement(sql);
                pstmt.setString(1,jTextField7.getText());
                pstmt.execute();
                JOptionPane.showMessageDialog(this,"users deleted");
            }
            
            
            
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
try {
            
            String sql ="update subject set sub_name = ?,credit =?,dept_id=? where sub_id= ?";
            PreparedStatement  pstmt = con.prepareStatement(sql);
            pstmt.setString(1,jTextField14.getText());
            pstmt.setString(2,jTextField15.getText());
            pstmt.setString(3,jTextField27.getText());
            pstmt.setString(4,jTextField26.getText());
            pstmt.execute();
            JOptionPane.showMessageDialog(this,"subject details updated");
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        jTabbedPane2.setSelectedIndex(0);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
                                    login login1 = new login();
                                    login1.setVisible(true);
                                    login1.pack();
                                    this.dispose();
                                    JOptionPane.showMessageDialog(this,"logout successfully");
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel39_id;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
