/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author others
 */
public class Lecturer extends javax.swing.JFrame {
    DatabaseConnection databaseConnection = new DatabaseConnection();
    Connection con = databaseConnection.myConnection();
    String depatment="";
    String a;
    /**
     * Creates new form Lecturer
     */
    public Lecturer() {
        initComponents();
    }
    public void lecture_id(String use) {
    a = use;
        jLabel48.setText(a);
        try {
            
            String sql ="select * from lecturer where lec_id= ?";
            PreparedStatement  pstmt = con.prepareStatement(sql);
            pstmt.setString(1,jLabel48.getText());
            
           ResultSet rs = pstmt.executeQuery();
           if(rs.next()){
           jLabel48.setText(a);
            jLabel49.setText(rs.getString("f_name"));
            jLabel50.setText(rs.getString("l_name"));
            jTextField10.setText(rs.getString("email"));
            jLabel51.setText(rs.getString("deparment"));
            jTextField11.setText(rs.getString("password"));
                depatment = rs.getString("deparment");
           }
            
            
            //String sql = "select * from subject where sub_id=?";            
            //PreparedStatement pstmt = con.prepareStatement(sql);
            //pstmt.setString(1,jTextField26.getText());
            //ResultSet rs = pstmt.executeQuery();
            //JOptionPane.showMessageDialog(this,"user details updated");
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel55 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel39 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel52 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jButton17 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255), 3));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lecturer PAGE");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Upload Marks");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student Details");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("New Notices");

        jButton1.setText("CAMarks");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Final Marks");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Basic Details");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Marks , GPA");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("notice ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton4.setText("Eligibility");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton10.setText("Attendance");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton22.setText("logout");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setText("profile ");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton23, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(77, 77, 77)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addContainerGap())))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton22)
                    .addComponent(jButton23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(11, 11, 11)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 290, 520));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("User ID");
        jPanel8.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, 30));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("First Name");
        jPanel8.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 120, 30));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Last Name");
        jPanel8.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 90, 30));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Email");
        jPanel8.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 120, 40));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Deparment");
        jPanel8.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 120, 40));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("jLabel48");
        jPanel8.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 180, 30));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("jLabel49");
        jPanel8.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 130, 20));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("jLabel50");
        jPanel8.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 200, 20));
        jPanel8.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 230, 30));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("jLabel51");
        jPanel8.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 230, 30));

        jButton14.setText("Upadate Profile");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 110, -1));

        jDesktopPane1.setLayer(jLabel55, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 150, 120));

        jButton15.setText("choose");
        jPanel8.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 140, -1));

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("jLabel57");
        jPanel8.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 100, 20));
        jPanel8.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 220, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/Capture.JPG"))); // NOI18N
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, -1, 510));

        jLabel53.setBackground(new java.awt.Color(0, 0, 0));
        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/ruhuna.jpg"))); // NOI18N
        jLabel53.setText("jLabel53");
        jPanel8.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 580, 40));

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/ruhuna.jpg"))); // NOI18N
        jPanel8.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 20, -1, 40));

        jTabbedPane2.addTab("tab1", jPanel8);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Upload CA marks");
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 190, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Student_id");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 140, 20));
        jPanel9.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 140, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Subject ID");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, 20));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel9.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 140, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Quiz 2");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 50, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Asignment 3");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Quiz 1");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Quiz 3");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Quiz 4");
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 70, 20));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Asignment 1");
        jPanel9.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Asignment 2");
        jPanel9.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));
        jPanel9.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 140, 30));
        jPanel9.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 140, 30));
        jPanel9.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 140, 30));
        jPanel9.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 140, 30));
        jPanel9.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 140, 30));
        jPanel9.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 140, 30));
        jPanel9.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 140, 30));

        jButton8.setText("update mark");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 120, 30));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Mid pratical");
        jPanel9.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 90, 20));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Mid Theory");
        jPanel9.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 80, 20));
        jPanel9.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 140, 30));
        jPanel9.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 140, 30));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("if your subject don't have  any one of this pust 0 for that");
        jPanel9.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, 40));

        jButton18.setText("insert mark");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 160, 30));

        jButton19.setText("view");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 140, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/Capture.JPG"))); // NOI18N
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Quiz 1");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jTabbedPane2.addTab("tab2", jPanel9);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Subject Id");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Student ID");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, 20));
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 320, 30));

        jButton9.setText("Update Marks");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 120, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Final pratical");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 90, -1));
        jPanel2.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 320, 30));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Final theory");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 90, -1));
        jPanel2.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 320, 30));
        jPanel2.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 320, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Upload Final Marks");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jButton20.setText("view");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 130, 30));

        jButton21.setText("add marks");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 100, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/Capture.JPG"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane2.addTab("tab3", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Student Id");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 130, 30));
        jPanel3.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 240, 30));

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 100, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Post", "student_id", "first name", "last name", "email", "Department"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 540, 50));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Basic Details of a Student");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 250, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/Capture.JPG"))); // NOI18N
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTextField9.setText("jTextField8");
        jPanel3.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 240, 30));

        jTabbedPane2.addTab("tab4", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Attendence eligible");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 210, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Subject Code", "pratical or theory", "Eligible or not"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 460, 110));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("CA Elilgible");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 190, 20));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Student Id");
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 130, 30));
        jPanel4.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 230, 30));

        jButton11.setText("view att eligible");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 130, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 460, 100));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Eligible Details  of a Student");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 380, 40));

        jButton16.setText("view  CA eligible");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 130, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/Capture.JPG"))); // NOI18N
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 575, 482));

        jTabbedPane2.addTab("tab5", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Final mark , SGPA ,CGPA");
        jPanel5.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 290, 50));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "subject id", "Final Marks", "gpa"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 490, 130));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Student Id");
        jPanel5.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, 30));
        jPanel5.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 210, 30));

        jButton12.setText("Search");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 80, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Final Marks,SGPA And CGPA of a Student");
        jPanel5.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 380, 30));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/Capture.JPG"))); // NOI18N
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane2.addTab("tab6", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Subject ID");
        jPanel6.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 30));

        jButton13.setText("Search");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 80, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Student Id");
        jPanel6.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, 30));
        jPanel6.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 210, 30));
        jPanel6.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 210, 30));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jPanel6.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 460, 270));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Attendance Details of a Student");
        jPanel6.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 290, 30));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/Capture.JPG"))); // NOI18N
        jLabel30.setText("search");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, -1));

        jTabbedPane2.addTab("tab7", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("View Notices");
        jPanel7.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "notice no", "topic", "date", "details"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        jPanel7.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, 220));

        jButton17.setText("view notices");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 50, 130, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/Capture.JPG"))); // NOI18N
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 470));

        jTabbedPane2.addTab("tab8", jPanel7);

        jPanel1.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 580, 510));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/login page2.jpg"))); // NOI18N
        jLabel1.setText("Time Table");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(6);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(3);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(4);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(5);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(7);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {            
            String sql = "select st_id,f_name,l_name,email,deparment from student where st_id=?";
            PreparedStatement pstmt = con.prepareStatement(sql);
            pstmt.setString(1,jTextField8.getText());
            ResultSet rs = pstmt.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException ex) {
            Logger.getLogger(Lecturer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        String depatment="";     
               
            
            
           
            
        
        
        String st = jTextField20.getText();
        if ( "d01".equals(depatment) ){
            try {
                String sql = "select sub_id,p_or_t,eli_nom,eli_med from ict_att_eli where st_id=?";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.setString(1,st);
                ResultSet rs = pstmt.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (SQLException ex) {
                Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if ( "d02".equals(depatment) ){
             try {
                String sql = "select * from ent_att_eli where st_id=?";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.setString(1,st);
                ResultSet rs = pstmt.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (SQLException ex) {
                Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if ( "d03".equals(depatment) ){
            try {
                String sql = "select * from bst_att_eli where st_id=?";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.setString(1,st);
                ResultSet rs = pstmt.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (SQLException ex) {
                Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        String depatment="";     
        try {            
            String sql1 = "select st_id,f_name,l_name,email,deparment from student where st_id=?";
            PreparedStatement pstmt1 = con.prepareStatement(sql1);
            pstmt1.setString(1,jTextField20.getText());
            ResultSet rs1 = pstmt1.executeQuery();
            if(rs1.next()){
                depatment = rs1.getString("deparment");
            } else {
            }
            
           
            
        
        
        String st = jTextField20.getText();
        if ( "d01".equals(depatment) ){
            try {
                String sql = "select sub_id,ca_st from ict_ca_eli where st_id=?";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.setString(1,st);
                ResultSet rs = pstmt.executeQuery();
                jTable3.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (SQLException ex) {
                Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if ( "d02".equals(depatment) ){
             try {
                String sql = "select sub_id,ca_st from ict_ca_eli where st_id=?";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.setString(1,st);
                ResultSet rs = pstmt.executeQuery();
                jTable3.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (SQLException ex) {
                Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if ( "d03".equals(depatment) ){
            try {
                String sql ="select sub_id,ca_st from ict_ca_eli where st_id=?";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.setString(1,st);
                ResultSet rs = pstmt.executeQuery();
                jTable3.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (SQLException ex) {
                Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        } catch (SQLException ex) {
            Logger.getLogger(Lecturer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        String depatment="";
        try {
            String sql1 = "select st_id,f_name,l_name,email,deparment from student where st_id=?";
            PreparedStatement pstmt1 = con.prepareStatement(sql1);
            pstmt1.setString(1,jTextField21.getText());
            ResultSet rs1 = pstmt1.executeQuery();
            if(rs1.next()){
                depatment = rs1.getString("deparment");
            } else {
            }
            String st = jTextField21.getText();
            
            
            if ( "d01".equals(depatment) ){
                try {
                    String sql = "select sub_id,final_mark,sgpa,cgpa from ict_all where st_id=?";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,st);
                    ResultSet rs = pstmt.executeQuery();
                    jTable4.setModel(DbUtils.resultSetToTableModel(rs));
                } catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if ( "d02".equals(depatment) ){
                try {
                    String sql = "select sub_id,final_mark,sgpa,cgpa from ent_all where st_id=?";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,st);
                    ResultSet rs = pstmt.executeQuery();
                    jTable4.setModel(DbUtils.resultSetToTableModel(rs));
                } catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if ( "d03".equals(depatment) ){
                try {
                    String sql = "select sub_id,final_mark,sgpa,cgpa from bst_all where st_id=?";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,st);
                    ResultSet rs = pstmt.executeQuery();
                    jTable4.setModel(DbUtils.resultSetToTableModel(rs));
                } catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Lecturer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        String depatment="";
        try {
            String sql1 = "select st_id,f_name,l_name,email,deparment from student where st_id=?";
            PreparedStatement pstmt1 = con.prepareStatement(sql1);
            pstmt1.setString(1,jTextField22.getText());
            ResultSet rs1 = pstmt1.executeQuery();
            if(rs1.next()){
                depatment = rs1.getString("deparment");
            } else {
            }
            String st = jTextField22.getText();
            String sb = jTextField23.getText();
            
            if ( "d01".equals(depatment) ){
                try {
                    String sql = "select p_or_t,total_pre,med,eli_nom,eli_med from ict_att_eli where st_id=? and sub_id=?";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,st);
                    pstmt.setString(2,sb);
                    ResultSet rs = pstmt.executeQuery();
                    jTable5.setModel(DbUtils.resultSetToTableModel(rs));
                } catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if ( "d02".equals(depatment) ){
                try {
                    String sql = "select p_or_t,total_pre,med,eli_nom,eli_med from ent_att_eli where st_id=? and sub_id=?";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,st);
                    pstmt.setString(2,sb);
                    ResultSet rs = pstmt.executeQuery();
                    jTable5.setModel(DbUtils.resultSetToTableModel(rs));
                } catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if ( "d03".equals(depatment) ){
                try {
                    String sql = "select p_or_t,total_pre,med,eli_nom,eli_med from bst_att_eli where st_id=? and sub_id=?";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,st);
                    pstmt.setString(2,sb);
                    ResultSet rs = pstmt.executeQuery();
                    jTable5.setModel(DbUtils.resultSetToTableModel(rs));
                } catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Lecturer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        try {
            String sql = "select * from notice";
            PreparedStatement pstmt = con.prepareStatement(sql);            
            ResultSet rs = pstmt.executeQuery();
            jTable6.setModel(DbUtils.resultSetToTableModel(rs));
                    } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
         try {
            // TODO add your handling code here:
            String sql ="update lecturer set password = ? , email = ? where lec_id = ?";
            PreparedStatement  pstmt = con.prepareStatement(sql);
            
            //pstmt.setString(1,jTextField13.getText());
            pstmt.setString(1,jTextField11.getText());
            pstmt.setString(2,jTextField10.getText());
            pstmt.setString(3,jLabel48.getText());
            
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this,"users details updated");
        } catch (SQLException ex) {
            Logger.getLogger(Technical.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        String st = jTextField1.getText();
        String sb = jTextField2.getText();
        if ( "d01".equals(depatment) ){
                try {
                    String sql = "select * from ict_ca_marks where st_id=? and sub_id=?";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,st);
                    pstmt.setString(2,sb);
                    ResultSet rs = pstmt.executeQuery();
                    if (rs.next()){
                        jTextField6.setText(rs.getString("q1"));
                        jTextField12.setText(rs.getString("q2"));
                        jTextField13.setText(rs.getString("q3"));
                        jTextField14.setText(rs.getString("q4"));
                        
                        jTextField4.setText(rs.getString("a1"));
                        jTextField3.setText(rs.getString("a2"));
                        jTextField5.setText(rs.getString("a3"));
                        
                        jTextField15.setText(rs.getString("m_p"));
                        jTextField16.setText(rs.getString("m_t"));
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if ( "d02".equals(depatment) ){
                try {
                    String sql ="select * from ent_ca_marks where st_id=? and sub_id=?";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,st);
                    pstmt.setString(2,sb);
                    ResultSet rs = pstmt.executeQuery();
                   if (rs.next()){
                        jTextField6.setText(rs.getString("q1"));
                        jTextField12.setText(rs.getString("q2"));
                        jTextField13.setText(rs.getString("q3"));
                        jTextField14.setText(rs.getString("q4"));
                        
                        jTextField4.setText(rs.getString("a1"));
                        jTextField3.setText(rs.getString("a2"));
                        jTextField5.setText(rs.getString("a3"));
                        
                        jTextField15.setText(rs.getString("m_p"));
                        jTextField16.setText(rs.getString("m_t"));
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if ( "d03".equals(depatment) ){
                try {
                    String sql = "select * from bst_ca_marks where st_id=? and sub_id=?";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,st);
                    pstmt.setString(2,sb);
                    ResultSet rs = pstmt.executeQuery();
                    if (rs.next()){
                        jTextField6.setText(rs.getString("q1"));
                        jTextField12.setText(rs.getString("q2"));
                        jTextField13.setText(rs.getString("q3"));
                        jTextField14.setText(rs.getString("q4"));
                        
                        jTextField4.setText(rs.getString("a1"));
                        jTextField3.setText(rs.getString("a2"));
                        jTextField5.setText(rs.getString("a3"));
                        
                        jTextField15.setText(rs.getString("m_p"));
                        jTextField16.setText(rs.getString("m_t"));
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }       
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        String st = jTextField1.getText();
        String sb = jTextField2.getText();
        int q1 = Integer.parseInt(jTextField6.getText());
        int q2= Integer.parseInt(jTextField12.getText());
        int q3 = Integer.parseInt(jTextField13.getText());
        int q4 = Integer.parseInt(jTextField14.getText());
        int a1 = Integer.parseInt(jTextField4.getText());
        int a2 = Integer.parseInt(jTextField3.getText());
        int a3 = Integer.parseInt(jTextField5.getText());
        int m_p = Integer.parseInt(jTextField15.getText());
        int m_t = Integer.parseInt(jTextField16.getText());
        if ( "d01".equals(depatment) ){
                try {
                    String sql = " insert into ict_ca_marks values(?,?,?,?,?,?,?,?,?,?,?)";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,st);
                    pstmt.setString(2,sb);
                    pstmt.setInt(3,q1);
                    pstmt.setInt(4,q2);
                    pstmt.setInt(5,q3);
                    pstmt.setInt(6,q4);
                    pstmt.setInt(7,a1);
                    pstmt.setInt(8,a2);
                    pstmt.setInt(9,a3);
                    pstmt.setInt(10,m_t);
                    pstmt.setInt(11,m_p);
                    
                    
                    
                    pstmt.execute();
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if ( "d02".equals(depatment) ){
                try {
                    String sql = " insert into ent_ca_marks values(?,?,?,?,?,?,?,?,?,?,?)";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,st);
                    pstmt.setString(2,sb);
                    pstmt.setInt(3,q1);
                    pstmt.setInt(4,q2);
                    pstmt.setInt(5,q3);
                    pstmt.setInt(6,q4);
                    pstmt.setInt(7,a1);
                    pstmt.setInt(8,a2);
                    pstmt.setInt(9,a3);
                    pstmt.setInt(10,m_t);
                    pstmt.setInt(11,m_p);
                    
                    
                    
                    pstmt.execute();
                    }
                 catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if ( "d03".equals(depatment) ){
                try {
                    String sql = " insert into bst_ca_marks values(?,?,?,?,?,?,?,?,?,?,?)";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,st);
                    pstmt.setString(2,sb);
                    pstmt.setInt(3,q1);
                    pstmt.setInt(4,q2);
                    pstmt.setInt(5,q3);
                    pstmt.setInt(6,q4);
                    pstmt.setInt(7,a1);
                    pstmt.setInt(8,a2);
                    pstmt.setInt(9,a3);
                    pstmt.setInt(10,m_t);
                    pstmt.setInt(11,m_p);
                    
                    
                    
                    pstmt.execute();
                    }
                 catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String st = jTextField1.getText();
        String sb = jTextField2.getText();
        int q1 = Integer.parseInt(jTextField6.getText());
        int q2= Integer.parseInt(jTextField12.getText());
        int q3 = Integer.parseInt(jTextField13.getText());
        int q4 = Integer.parseInt(jTextField14.getText());
        int a1 = Integer.parseInt(jTextField4.getText());
        int a2 = Integer.parseInt(jTextField3.getText());
        int a3 = Integer.parseInt(jTextField5.getText());
        int m_p = Integer.parseInt(jTextField15.getText());
        int m_t = Integer.parseInt(jTextField16.getText());
        if ( "d01".equals(depatment) ){
                try {
                    String sql = " update ict_ca_marks set q1=?,q2=?,q3=?,q4=?,a1=?,a2=?,a3=?,m_p=?,m_t=? where st_id=? and sub_id=? ";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    
                    pstmt.setInt(1,q1);
                    pstmt.setInt(2,q2);
                    pstmt.setInt(3,q3);
                    pstmt.setInt(4,q4);
                    pstmt.setInt(5,a1);
                    pstmt.setInt(6,a2);
                    pstmt.setInt(7,a3);
                    pstmt.setInt(8,m_t);
                    pstmt.setInt(9,m_p);
                    pstmt.setString(10,st);
                    pstmt.setString(11,sb);
                    
                    
                    
                    pstmt.executeUpdate();
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if ( "d02".equals(depatment) ){
                try {
                    String sql = " update ent_ca_marks set q1=?,q2=?,q3=?,q4=?,a1=?,a2=?,a3=?,m_p=?,m_t=? where st_id=? and sub_id=? ";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    
                    pstmt.setInt(1,q1);
                    pstmt.setInt(2,q2);
                    pstmt.setInt(3,q3);
                    pstmt.setInt(4,q4);
                    pstmt.setInt(5,a1);
                    pstmt.setInt(6,a2);
                    pstmt.setInt(7,a3);
                    pstmt.setInt(8,m_t);
                    pstmt.setInt(9,m_p);
                    pstmt.setString(10,st);
                    pstmt.setString(11,sb);
                    
                    
                    
                    pstmt.executeUpdate();
                    }
                 catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if ( "d03".equals(depatment) ){
                try {
                    String sql = " update bst_ca_marks set q1=?,q2=?,q3=?,q4=?,a1=?,a2=?,a3=?,m_p=?,m_t=? where st_id=? and sub_id=? ";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    
                    pstmt.setInt(1,q1);
                    pstmt.setInt(2,q2);
                    pstmt.setInt(3,q3);
                    pstmt.setInt(4,q4);
                    pstmt.setInt(5,a1);
                    pstmt.setInt(6,a2);
                    pstmt.setInt(7,a3);
                    pstmt.setInt(8,m_t);
                    pstmt.setInt(9,m_p);
                    pstmt.setString(10,st);
                    pstmt.setString(11,sb);
                    
                    
                    
                    pstmt.executeUpdate();
                    }
                 catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String st = jTextField7.getText();
        String sb = jTextField17.getText();
        int f_t = Integer.parseInt(jTextField18.getText());
        int f_p= Integer.parseInt(jTextField19.getText());
        
        if ( "d01".equals(depatment) ){
                try {
                    String sql = " update ict_fi_exam_marks set fi_t=?,fi_p=? where st_id=? and sub_id=? ";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    
                    pstmt.setInt(1,f_t);
                    pstmt.setInt(2,f_p);
                   
                    pstmt.setString(3,st);
                    pstmt.setString(4,sb);
                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(this,"marks added to ict final marks");
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if ( "d02".equals(depatment) ){
                try {
                    String sql = " update ent_fi_exam_marks set fi_t=?,fi_p=? where st_id=? and sub_id=? ";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    
                    pstmt.setInt(1,f_t);
                    pstmt.setInt(2,f_p);
                   
                    pstmt.setString(3,st);
                    pstmt.setString(4,sb);
                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(this,"marks added to Ent final marks");
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if ( "d03".equals(depatment) ){
                try {
                    String sql = " update bst_fi_exam_marks set fi_t=?,fi_p=? where st_id=? and sub_id=? ";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    
                    pstmt.setInt(1,f_t);
                    pstmt.setInt(2,f_p);
                   
                    pstmt.setString(3,st);
                    pstmt.setString(4,sb);
                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(this,"marks added to bst final marks");
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
         String st = jTextField7.getText();
        String sb = jTextField17.getText();
        if ( "d01".equals(depatment) ){
                try {
                    String sql = "select * from ict_fi_exam_marks where st_id=? and sub_id=?";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,st);
                    pstmt.setString(2,sb);
                    ResultSet rs = pstmt.executeQuery();
                    if (rs.next()){
                        jTextField18.setText(rs.getString("fi_t"));
                        jTextField19.setText(rs.getString("fi_p"));
                        
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if ( "d02".equals(depatment) ){
                try {
                    String sql = "select * from ent_fi_exam_marks where st_id=? and sub_id=?";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,st);
                    pstmt.setString(2,sb);
                    ResultSet rs = pstmt.executeQuery();
                    if (rs.next()){
                        jTextField18.setText(rs.getString("fi_t"));
                        jTextField19.setText(rs.getString("fi_p"));
                        
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if ( "d03".equals(depatment) ){
                try {
                    String sql = "select * from bst_fi_exam_marks where st_id=? and sub_id=?";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,st);
                    pstmt.setString(2,sb);
                    ResultSet rs = pstmt.executeQuery();
                    if (rs.next()){
                        jTextField18.setText(rs.getString("fi_t"));
                        jTextField19.setText(rs.getString("fi_p"));
                        
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        String st = jTextField7.getText();
        String sb = jTextField17.getText();
        int f_t = Integer.parseInt(jTextField18.getText());
        int f_p= Integer.parseInt(jTextField19.getText());
        
        
        if ( "d01".equals(depatment) ){
                try {
                    String sql = " insert into ict_fi_exam_marks values(?,?,?,?)";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,st);
                    pstmt.setString(2,sb);
                    pstmt.setInt(3,f_t);
                    pstmt.setInt(4,f_p);
                    
                    pstmt.execute();
                } catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if ( "d02".equals(depatment) ){
                try {
                     String sql = " insert into ent_fi_exam_marks values(?,?,?,?)";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,st);
                    pstmt.setString(2,sb);
                    pstmt.setInt(3,f_t);
                    pstmt.setInt(4,f_p);
                    
                    pstmt.execute();
                } catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if ( "d03".equals(depatment) ){
                try {
                     String sql = " insert into bst_fi_exam_marks values(?,?,?,?)";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    pstmt.setString(1,st);
                    pstmt.setString(2,sb);
                    pstmt.setInt(3,f_t);
                    pstmt.setInt(4,f_p);
                    pstmt.execute();
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        jTabbedPane2.setSelectedIndex(0);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
                                    login login1 = new login();
                                    login1.setVisible(true);
                                    login1.pack();
                                    this.dispose();
                                    JOptionPane.showMessageDialog(this,"logout successfully");
                                    
    }//GEN-LAST:event_jButton22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lecturer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    
}
