/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author others
 */
public class Student extends javax.swing.JFrame {
String depatment="";
String a;
    /**
     * Creates new form Student
     */
    
    DatabaseConnection databaseConnection = new DatabaseConnection();
    Connection con = databaseConnection.myConnection();
    
    public Student() {
        initComponents();
        setLocationRelativeTo(null);
    }

   public void student_id(String use){
       a = use;
        jLabel24_id.setText(a);
        try {
            
            String sql ="select * from student where st_id= ?";
            PreparedStatement  pstmt = con.prepareStatement(sql);
            pstmt.setString(1,jLabel24_id.getText());
            
           ResultSet rs = pstmt.executeQuery();
           if(rs.next()){
            jLabel24_id.setText(a);
            jLabel25_f_name.setText(rs.getString("f_name"));
            jLabel26.setText(rs.getString("l_name"));
            jTextField1.setText(rs.getString("email"));
            jLabel27.setText(rs.getString("deparment"));
            jTextField2.setText(rs.getString("password"));
            depatment = rs.getString("deparment");
           }
            
            
            //String sql = "select * from subject where sub_id=?";            
            //PreparedStatement pstmt = con.prepareStatement(sql);
            //pstmt.setString(1,jTextField26.getText());
            //ResultSet rs = pstmt.executeQuery();
            //JOptionPane.showMessageDialog(this,"user details updated");
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel19 = new javax.swing.JLabel();
        jLabel24_id = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel25_f_name = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel31 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLayeredPane7 = new javax.swing.JLayeredPane();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 153), 3, true));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student page");
        jLayeredPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Grade And GPA");
        jLayeredPane1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 190, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Course Details");
        jLayeredPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 160, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Time Table");
        jLayeredPane1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 170, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Notices");
        jLayeredPane1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 200, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Attendance Details");
        jLayeredPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 140, 20));

        jButton1.setText("Click to view Course details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 160, -1));

        jButton2.setText("Click to view eligible details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 160, -1));

        jButton3.setText("Click to view Grade And GPA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 160, -1));

        jButton4.setText("Click to view Time Table");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 160, -1));

        jButton5.setText("Click to view notices");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 160, -1));

        jButton14.setText("profile");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, -1));

        jButton15.setText("logout");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 60, 100, -1));

        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 510));

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("User ID");
        jLayeredPane2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 90, 20));

        jLabel24_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24_id.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24_id.setText("jLabel24");
        jLayeredPane2.add(jLabel24_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 160, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("First Name ");
        jLayeredPane2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 90, 20));

        jLabel25_f_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25_f_name.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25_f_name.setText("jLabel25");
        jLayeredPane2.add(jLabel25_f_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 130, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Last Name");
        jLabel21.setToolTipText("");
        jLayeredPane2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 90, 20));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("jLabel26");
        jLayeredPane2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 100, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Email");
        jLayeredPane2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, 30));
        jLayeredPane2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 170, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Department");
        jLayeredPane2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 110, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("jLabel27");
        jLayeredPane2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 170, 30));

        jButton6.setText("Update Profiile");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 140, 30));

        jLabel31.setText("jLabel31");

        jDesktopPane1.setLayer(jLabel31, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLayeredPane2.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 150, 110));

        jButton7.setText("choose");
        jLayeredPane2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 130, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("password");
        jLayeredPane2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 100, 20));

        jTextField2.setText("jTextField2");
        jLayeredPane2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 170, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/Capture.JPG"))); // NOI18N
        jLayeredPane2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/ruhuna.jpg"))); // NOI18N
        jLabel29.setText("jLabel29");
        jLayeredPane2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 40, 580, 50));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/ruhuna.jpg"))); // NOI18N
        jLayeredPane2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 50));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/ruhuna.jpg"))); // NOI18N
        jLabel25.setText("jLabel25");
        jLayeredPane2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 560, 40));

        jTabbedPane1.addTab("tab1", jLayeredPane2);

        jLayeredPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.MatteBorder(null)));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLayeredPane3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 530, 190));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("subject Details");
        jLayeredPane3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 170, 30));

        jButton8.setText("view subject details");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jLayeredPane3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 130, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/Capture.JPG"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLayeredPane3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("tab2", jLayeredPane3);

        jLayeredPane4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLayeredPane4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 480, 140));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Attendence eligible");
        jLayeredPane4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 270, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("CA Elilgible");
        jLayeredPane4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 190, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Eligible Details");
        jLayeredPane4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 250, 30));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLayeredPane4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 470, 130));

        jButton9.setText("view Attence");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jLayeredPane4.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 120, 30));

        jButton10.setText("view ca eligible");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jLayeredPane4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 243, 110, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/Capture.JPG"))); // NOI18N
        jLayeredPane4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("tab3", jLayeredPane4);

        jLayeredPane5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Final mark , SGPA ,CGPA");
        jLayeredPane5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 290, 50));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "subject id", "final mark"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jLayeredPane5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 440, 140));

        jButton11.setText("view final mark sgpa, cgpa");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jLayeredPane5.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 110, 170, 30));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("SGPA");
        jLayeredPane5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 80, 30));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("SGPA for you");
        jLayeredPane5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 140, 30));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("GPA");
        jLayeredPane5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 90, 30));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("jLabel36");
        jLayeredPane5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 80, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/Capture.JPG"))); // NOI18N
        jLayeredPane5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 470));

        jTabbedPane1.addTab("tab4", jLayeredPane5);

        jLayeredPane6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Time Table");
        jLayeredPane6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "time", "mon", "tue", "wen", "thu", "fri"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jLayeredPane6.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 480, 170));

        jButton12.setText("view time table");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jLayeredPane6.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 140, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/Capture.JPG"))); // NOI18N
        jLayeredPane6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("tab5", jLayeredPane6);

        jLayeredPane7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("View Notices");
        jLayeredPane7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 130, -1));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "notice no", "topic", "date", "details"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        jLayeredPane7.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 450, 220));

        jButton13.setText("view notice");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jLayeredPane7.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 110, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/Capture.JPG"))); // NOI18N
        jLayeredPane7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("tab6", jLayeredPane7);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 580, 490));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/photos/login page2.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            // TODO add your handling code here:
            
            String sql ="update student set password = ? , email = ? where st_id = ?";
            PreparedStatement  pstmt = con.prepareStatement(sql);
            
            //pstmt.setString(1,jTextField13.getText());
            pstmt.setString(1,jTextField2.getText());
            pstmt.setString(2,jTextField1.getText());
            pstmt.setString(3,jLabel24_id.getText());
            
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this,"users details updated");
        } catch (SQLException ex) {
            Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {            
            String sql = "select * from subject where dept_id=?";
            PreparedStatement pstmt = con.prepareStatement(sql);
            pstmt.setString(1,depatment);
            ResultSet rs = pstmt.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException ex) {
            Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if ( "d01".equals(depatment) ){
            try {
                String sql = "select * from ict_ca_eli where st_id=?";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.setString(1,a);
                ResultSet rs = pstmt.executeQuery();
                jTable3.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (SQLException ex) {
                Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if ( "d02".equals(depatment) ){
             try {
                String sql = "select * from ent_ca_eli where st_id=?";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.setString(1,a);
                ResultSet rs = pstmt.executeQuery();
                jTable3.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (SQLException ex) {
                Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if ( "d03".equals(depatment) ){
            try {
                String sql = "select * from bst_ca_eli where st_id=?";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.setString(1,a);
                ResultSet rs = pstmt.executeQuery();
                jTable3.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (SQLException ex) {
                Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if ( "d01".equals(depatment) ){
            try {
                String sql = "select sub_id,p_or_t,eli_nom,eli_med from ict_att_eli where st_id=?";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.setString(1,a);
                ResultSet rs = pstmt.executeQuery();
                jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (SQLException ex) {
                Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if ( "d02".equals(depatment) ){
             try {
                String sql = "select * from ent_att_eli where st_id=?";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.setString(1,a);
                ResultSet rs = pstmt.executeQuery();
                jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (SQLException ex) {
                Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if ( "d03".equals(depatment) ){
            try {
                String sql = "select * from bst_att_eli where st_id=?";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.setString(1,a);
                ResultSet rs = pstmt.executeQuery();
                jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (SQLException ex) {
                Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
         if ( "d01".equals(depatment) ){
            try {
                String sql = "select sub_id,final_mark from ict_all where st_id=?";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.setString(1,a);
                ResultSet rs = pstmt.executeQuery();
                jTable4.setModel(DbUtils.resultSetToTableModel(rs));
                
                String sql2 = "select st_id,sub_id,sgpa,cgpa from ict_all where st_id=? and sub_id=?";
                PreparedStatement pstmt2 = con.prepareStatement(sql2);
                String sub_1="ict0001";
                pstmt2.setString(1,a);
                pstmt2.setString(2,sub_1);
                ResultSet rs2 = pstmt2.executeQuery();
               if(rs2.next()){
            jLabel34.setText(rs2.getString("sgpa"));
            jLabel36.setText(rs2.getString("cgpa"));
               }
                
            } catch (SQLException ex) {
                Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if ( "d02".equals(depatment) ){
             try {
                String sql = "select sub_id,final_mark from ent_all where st_id=?";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.setString(1,a);
                ResultSet rs = pstmt.executeQuery();
                jTable4.setModel(DbUtils.resultSetToTableModel(rs));
                
                String sql2 = "select st_id,sub_id,sgpa,cgpa from ent_all where st_id=? and sub_id=?";
                PreparedStatement pstmt2 = con.prepareStatement(sql2);
                String sub_1="ent0001";
                pstmt2.setString(1,a);
                pstmt2.setString(2,sub_1);
                ResultSet rs2 = pstmt2.executeQuery();
               if(rs2.next()){
            jLabel34.setText(rs2.getString("sgpa"));
            jLabel36.setText(rs2.getString("cgpa"));
               }
            } catch (SQLException ex) {
                Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if ( "d03".equals(depatment) ){
            try {
                String sql = "select sub_id,final_mark from bst_all where st_id=?";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.setString(1,a);
                ResultSet rs = pstmt.executeQuery();
                jTable4.setModel(DbUtils.resultSetToTableModel(rs));
                
                String sql2 = "select st_id,sub_id,sgpa,cgpa from bst_all where st_id=? and sub_id=?";
                PreparedStatement pstmt2 = con.prepareStatement(sql2);
                String sub_1="bst0001";
                pstmt2.setString(1,a);
                pstmt2.setString(2,sub_1);
                ResultSet rs2 = pstmt2.executeQuery();
               if(rs2.next()){
            jLabel34.setText(rs2.getString("sgpa"));
            jLabel36.setText(rs2.getString("cgpa"));
               }
                
            } catch (SQLException ex) {
                Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
        if( "d01".equals(depatment) ){
            
            
                String sql = "select * from ict_time_table";
                
                PreparedStatement pstmt = con.prepareStatement(sql);
                ResultSet rs = pstmt.executeQuery();
                jTable5.setModel(DbUtils.resultSetToTableModel(rs));
            
            }
            if( "d02".equals(depatment) ){
            
            String sql = "select * from ent_time_table";
            
            PreparedStatement pstmt = con.prepareStatement(sql);            
            ResultSet rs = pstmt.executeQuery();
            jTable5.setModel(DbUtils.resultSetToTableModel(rs));
            }
            if( "d03".equals(depatment) ){
            
            String sql = "select * from bst_time_table";
            
            PreparedStatement pstmt = con.prepareStatement(sql);            
            ResultSet rs = pstmt.executeQuery();
            jTable5.setModel(DbUtils.resultSetToTableModel(rs));
            }
            } catch (SQLException ex) {
                Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try {
            String sql = "select * from notice";
            PreparedStatement pstmt = con.prepareStatement(sql);            
            ResultSet rs = pstmt.executeQuery();
            jTable6.setModel(DbUtils.resultSetToTableModel(rs));
                    } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
                                    login login1 = new login();
                                    login1.setVisible(true);
                                    login1.pack();
                                    this.dispose();
                                    JOptionPane.showMessageDialog(this,"logout successfully");
    }//GEN-LAST:event_jButton15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel24_id;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel25_f_name;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JLayeredPane jLayeredPane7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

   

 
}
